language: cpp

compiler:
  - gcc
  - clang 

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install libopenmpi-dev
  - sudo apt-get install libargtable2-dev

script: 
  - mkdir build
  - cd build 
  - cmake ../
  - make  
